name: flutter_foodstore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/fries.png
    - lib/assets/images/soda.png
    - lib/assets/images/xburger.png
    - lib/assets/images/xegg.png
    - lib/assets/images/xbacon.png
